version: '3'

services:
    db:
        image: tsooqexampledb:latest
        volumes:
         - db_data:/var/lib/postgresql/data
         - db_log:/var/log/postgresql
        restart: always
        ports:
         - "5432:5432"
         
volumes:
    db_data:
    db_log:
